
export const constellInfo = {"Ursa Minor" : "Ursa Minor (Latin for Lesser Bear, contrasting with Ursa Major), also known as the Little Bear, is a constellation in the Northern Sky. Like the Great Bear, the tail of the Little Bear may also be seen as the handle of a ladle, hence the North American name, Little Dipper: seven stars with four in its bowl like its partner the Big Dipper. It was one of the 48 constellations listed by the 2nd-century astronomer Ptolemy, and remains one of the 88 modern constellations. Ursa Minor has traditionally been important for navigation, particularly by mariners, because of Polaris being the north pole star.",
"Draco" :  "DRAGON",
"Lyra" : "harp",
"Cepheus" : "wut",
"Cassiopeia" : "wut",
"Camelopardalis" : "wut",
"Lynx" : "wut",
"Ursa Major" : "wut",
"Virgo": "wut",
"Serpens": "wut",
"Coma Berenices": "wut",
"Canes Venatici": "wut",
"Corona Borealis": "wut",
"Boötes": "wut",
"Hercules": "wut",
"Ophiuchus": "wut",
"Lacerta": "wut",
"Vulpecula": "wut",
"Sagitta": "wut",
"Cygnus": "wut",
"Aquila": "wut",
"Delphinus": "wut",
"Pegasus": "wut",
"Andromeda": "wut",
"Equuelus": "wut",
"Perseus": "wut",
"Triangulum": "wut",
"Aries": "wut",
"Cetus": "wut",
"Pisces": "wut",
"Taurus": "wut",
"Auriga": "wut",
"Orion": "wut",
"Leo": "wut",
"Leo Minor": "wut",
"Hydra": "wut",
"Cancer": "wut",
"Canis Minor": "wut",
"Gemini": "wut",
"Monoceros": "wut",
}


