
export const constellInfo = {"Ursa Minor" : "SMALL BEAR",
"Draco" :  "DRAGON",
"Lyra" : "harp",
"Cepheus" : "wut",
"Cassiopeia" : "wut",
"Camelopardalis" : "wut",
"Lynx" : "wut",
"Ursa Major" : "wut",
"Virgo": "wut",
"Serpens": "wut",
"Coma Berenices": "wut",
"Canes Venatici": "wut",
"Corona Borealis": "wut",
"Boötes": "wut",
"Hercules": "wut",
"Ophiuchus": "wut",
"Lacerta": "wut",
"Vulpecula": "wut",
"Sagitta": "wut",
"Cygnus": "wut",
"Aquila": "wut",
"Delphinus": "wut",
"Pegasus": "wut",
"Andromeda": "wut",
"Equuelus": "wut",
"Perseus": "wut",
"Triangulum": "wut",
"Aries": "wut",
"Cetus": "wut",
"Pisces": "wut",
"Taurus": "wut",
"Auriga": "wut",
"Orion": "wut",
"Leo": "wut",
"Leo Minor": "wut",
"Hydra": "wut",
"Cancer": "wut",
"Canis Minor": "wut",
"Gemini": "wut",
"Monoceros": "wut",
}


